language: java
sudo: false

jobs:
  include:
    - stage: "Unit Test"
      script: "mvn test"
    - stage: "Compilation Test"
      script: 
      - "mvn clean package"
      - "java -jar ./target/spring_sample_xml-1.0-SNAPSHOT.jar" 
    - stage: "Deploy"
      script: "echo todo: call mvn deploy"